import api from './api';

/**
 * Relationship service wrapper
 */
const relationshipService = {
  /**
   * Generate an invite code for pairing
   */
  createInvite: async () => {
    const response = await api.post('/partner/create-invite');
    return response.data;
  },

  /**
   * Get currently active invite code generated by user
   */
  getInvite: async () => {
    const response = await api.get('/partner/my-invite');
    return response.data;
  },

  /**
   * Connect with a partner using their invite code
   */
  joinRelationship: async (code) => {
    const response = await api.post('/partner/join', { code });
    return response.data;
  },

  /**
   * Fetch pairing status and partner details
   */
  getStatus: async () => {
    const response = await api.get('/partner/status');
    return response.data;
  },

  /**
   * Disconnect the relationship
   */
  disconnect: async () => {
    const response = await api.delete('/partner/disconnect');
    return response.data;
  },

  /**
   * Regenerate active invite code
   */
  regenerateInvite: async () => {
    const response = await api.post('/partner/regenerate');
    return response.data;
  },
};

export default relationshipService;
